services:
  igar:
    container_name: ab-market-dev
    build:
      context: .
      dockerfile: .dev.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/opt/app
      - /opt/app/cache
      - /opt/app/node_modules
    environment:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: "1"
      HOSTNAME: 0.0.0.0
      PORT: 3000
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    restart: unless-stopped
